-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (AuthResponse(..), Position(..), Submission(..), Tag(..), Topic(..), Transition(..), User(..))


type AuthResponse
    = AuthResponse


type Position
    = Position


type Submission
    = Submission


type Tag
    = Tag


type Topic
    = Topic


type Transition
    = Transition


type User
    = User
