-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object exposing (..)


type AuthResponse
    = AuthResponse


type Position
    = Position


type Submission
    = Submission


type Tag
    = Tag


type Topic
    = Topic


type Transition
    = Transition


type User
    = User
