-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Api.Object.Tag exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Api.Object
import Api.Interface
import Api.Union
import Api.Scalar
import Api.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Tag
selection constructor =
    Object.selection constructor
{-| 
-}
id : Field Api.Scalar.Id Api.Object.Tag
id =
      Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map Api.Scalar.Id)


{-| 
-}
name : Field String Api.Object.Tag
name =
      Object.fieldDecoder "name" [] (Decode.string)


{-| 
-}
submissions : SelectionSet decodesTo Api.Object.Submission -> Field (List decodesTo) Api.Object.Tag
submissions object_ =
      Object.selectionField "submissions" [] (object_) (identity >> Decode.list)


{-| 
-}
transitions : SelectionSet decodesTo Api.Object.Transition -> Field (List decodesTo) Api.Object.Tag
transitions object_ =
      Object.selectionField "transitions" [] (object_) (identity >> Decode.list)
