-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.User exposing (PositionsOptionalArguments, SubmissionsOptionalArguments, TagsOptionalArguments, TopicsOptionalArguments, TransitionsOptionalArguments, createdAt, email, id, password, positions, selection, submissions, tags, topics, transitions, updatedAt)

import Api.Enum.PositionOrderByInput
import Api.Enum.SubmissionOrderByInput
import Api.Enum.TagOrderByInput
import Api.Enum.TopicOrderByInput
import Api.Enum.TransitionOrderByInput
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.User
selection constructor =
    Object.selection constructor


{-| -}
id : Field Api.Scalar.Id Api.Object.User
id =
    Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map Api.Scalar.Id)


{-| -}
createdAt : Field Api.Scalar.DateTime Api.Object.User
createdAt =
    Object.fieldDecoder "createdAt" [] (Object.scalarDecoder |> Decode.map Api.Scalar.DateTime)


{-| -}
updatedAt : Field Api.Scalar.DateTime Api.Object.User
updatedAt =
    Object.fieldDecoder "updatedAt" [] (Object.scalarDecoder |> Decode.map Api.Scalar.DateTime)


{-| -}
email : Field String Api.Object.User
email =
    Object.fieldDecoder "email" [] Decode.string


{-| -}
password : Field String Api.Object.User
password =
    Object.fieldDecoder "password" [] Decode.string


type alias PositionsOptionalArguments =
    { where_ : OptionalArgument Api.InputObject.PositionWhereInput, orderBy : OptionalArgument Api.Enum.PositionOrderByInput.PositionOrderByInput, skip : OptionalArgument Int, after : OptionalArgument String, before : OptionalArgument String, first : OptionalArgument Int, last : OptionalArgument Int }


{-|

  - where\_ -
  - orderBy -
  - skip -
  - after -
  - before -
  - first -
  - last -

-}
positions : (PositionsOptionalArguments -> PositionsOptionalArguments) -> SelectionSet decodesTo Api.Object.Position -> Field (Maybe (List decodesTo)) Api.Object.User
positions fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { where_ = Absent, orderBy = Absent, skip = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs =
            [ Argument.optional "where" filledInOptionals.where_ Api.InputObject.encodePositionWhereInput, Argument.optional "orderBy" filledInOptionals.orderBy (Encode.enum Api.Enum.PositionOrderByInput.toString), Argument.optional "skip" filledInOptionals.skip Encode.int, Argument.optional "after" filledInOptionals.after Encode.string, Argument.optional "before" filledInOptionals.before Encode.string, Argument.optional "first" filledInOptionals.first Encode.int, Argument.optional "last" filledInOptionals.last Encode.int ]
                |> List.filterMap identity
    in
    Object.selectionField "positions" optionalArgs object_ (identity >> Decode.list >> Decode.nullable)


type alias SubmissionsOptionalArguments =
    { where_ : OptionalArgument Api.InputObject.SubmissionWhereInput, orderBy : OptionalArgument Api.Enum.SubmissionOrderByInput.SubmissionOrderByInput, skip : OptionalArgument Int, after : OptionalArgument String, before : OptionalArgument String, first : OptionalArgument Int, last : OptionalArgument Int }


{-|

  - where\_ -
  - orderBy -
  - skip -
  - after -
  - before -
  - first -
  - last -

-}
submissions : (SubmissionsOptionalArguments -> SubmissionsOptionalArguments) -> SelectionSet decodesTo Api.Object.Submission -> Field (Maybe (List decodesTo)) Api.Object.User
submissions fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { where_ = Absent, orderBy = Absent, skip = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs =
            [ Argument.optional "where" filledInOptionals.where_ Api.InputObject.encodeSubmissionWhereInput, Argument.optional "orderBy" filledInOptionals.orderBy (Encode.enum Api.Enum.SubmissionOrderByInput.toString), Argument.optional "skip" filledInOptionals.skip Encode.int, Argument.optional "after" filledInOptionals.after Encode.string, Argument.optional "before" filledInOptionals.before Encode.string, Argument.optional "first" filledInOptionals.first Encode.int, Argument.optional "last" filledInOptionals.last Encode.int ]
                |> List.filterMap identity
    in
    Object.selectionField "submissions" optionalArgs object_ (identity >> Decode.list >> Decode.nullable)


type alias TransitionsOptionalArguments =
    { where_ : OptionalArgument Api.InputObject.TransitionWhereInput, orderBy : OptionalArgument Api.Enum.TransitionOrderByInput.TransitionOrderByInput, skip : OptionalArgument Int, after : OptionalArgument String, before : OptionalArgument String, first : OptionalArgument Int, last : OptionalArgument Int }


{-|

  - where\_ -
  - orderBy -
  - skip -
  - after -
  - before -
  - first -
  - last -

-}
transitions : (TransitionsOptionalArguments -> TransitionsOptionalArguments) -> SelectionSet decodesTo Api.Object.Transition -> Field (Maybe (List decodesTo)) Api.Object.User
transitions fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { where_ = Absent, orderBy = Absent, skip = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs =
            [ Argument.optional "where" filledInOptionals.where_ Api.InputObject.encodeTransitionWhereInput, Argument.optional "orderBy" filledInOptionals.orderBy (Encode.enum Api.Enum.TransitionOrderByInput.toString), Argument.optional "skip" filledInOptionals.skip Encode.int, Argument.optional "after" filledInOptionals.after Encode.string, Argument.optional "before" filledInOptionals.before Encode.string, Argument.optional "first" filledInOptionals.first Encode.int, Argument.optional "last" filledInOptionals.last Encode.int ]
                |> List.filterMap identity
    in
    Object.selectionField "transitions" optionalArgs object_ (identity >> Decode.list >> Decode.nullable)


type alias TopicsOptionalArguments =
    { where_ : OptionalArgument Api.InputObject.TopicWhereInput, orderBy : OptionalArgument Api.Enum.TopicOrderByInput.TopicOrderByInput, skip : OptionalArgument Int, after : OptionalArgument String, before : OptionalArgument String, first : OptionalArgument Int, last : OptionalArgument Int }


{-|

  - where\_ -
  - orderBy -
  - skip -
  - after -
  - before -
  - first -
  - last -

-}
topics : (TopicsOptionalArguments -> TopicsOptionalArguments) -> SelectionSet decodesTo Api.Object.Topic -> Field (Maybe (List decodesTo)) Api.Object.User
topics fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { where_ = Absent, orderBy = Absent, skip = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs =
            [ Argument.optional "where" filledInOptionals.where_ Api.InputObject.encodeTopicWhereInput, Argument.optional "orderBy" filledInOptionals.orderBy (Encode.enum Api.Enum.TopicOrderByInput.toString), Argument.optional "skip" filledInOptionals.skip Encode.int, Argument.optional "after" filledInOptionals.after Encode.string, Argument.optional "before" filledInOptionals.before Encode.string, Argument.optional "first" filledInOptionals.first Encode.int, Argument.optional "last" filledInOptionals.last Encode.int ]
                |> List.filterMap identity
    in
    Object.selectionField "topics" optionalArgs object_ (identity >> Decode.list >> Decode.nullable)


type alias TagsOptionalArguments =
    { where_ : OptionalArgument Api.InputObject.TagWhereInput, orderBy : OptionalArgument Api.Enum.TagOrderByInput.TagOrderByInput, skip : OptionalArgument Int, after : OptionalArgument String, before : OptionalArgument String, first : OptionalArgument Int, last : OptionalArgument Int }


{-|

  - where\_ -
  - orderBy -
  - skip -
  - after -
  - before -
  - first -
  - last -

-}
tags : (TagsOptionalArguments -> TagsOptionalArguments) -> SelectionSet decodesTo Api.Object.Tag -> Field (Maybe (List decodesTo)) Api.Object.User
tags fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { where_ = Absent, orderBy = Absent, skip = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs =
            [ Argument.optional "where" filledInOptionals.where_ Api.InputObject.encodeTagWhereInput, Argument.optional "orderBy" filledInOptionals.orderBy (Encode.enum Api.Enum.TagOrderByInput.toString), Argument.optional "skip" filledInOptionals.skip Encode.int, Argument.optional "after" filledInOptionals.after Encode.string, Argument.optional "before" filledInOptionals.before Encode.string, Argument.optional "first" filledInOptionals.first Encode.int, Argument.optional "last" filledInOptionals.last Encode.int ]
                |> List.filterMap identity
    in
    Object.selectionField "tags" optionalArgs object_ (identity >> Decode.list >> Decode.nullable)
